#!/usr/bin/env bash
java -jar target/catalyst-hello.jar put CAmapq2rw8kdkKrEeEcjPXcLnpuvGdyAWzPyRJU8VmguxwNvqGqgxAfFmZ4qyE8XTtUqddJcMgPRZ9GCe5aNpVc7mv8gct5wrFJaBbVF2G2bqqhJTTFfQPYXMR8aPGRgUdRVJJh5m2Wb7WdhSRLNgL5naU4BcPXkVfaxGHTMAekPMC9z7wZnaSBCMcPAvB99sHkBFPwQ6SHKqv7BNQQ8EAD2yuRJsBRzTWmDgPBr5wFVFnYK3vsSuXWFaRSWZQBW
